In [15]:
from pathlib import Path
import pandas as pd
import numpy as np

# Main LUAD project folder
PROJECT_DIR = Path(
    r"C:\Users\LAPTOP\Downloads\luad_reserch_code"
)

# Seven cohorts
COHORTS = [
    "TCGA_Atlas_2018",
    "LUNG_MSK_2017",
    "MSK_NPJPO_2021",
    "MSKCC_2020",
    "MSKCC_2023",
    "NCI_2022",
    "ONCOSG_2020"
]

print("Project folder exists:", PROJECT_DIR.exists())
print("Project folder:", PROJECT_DIR)
print("Number of cohorts:", len(COHORTS))
print("Cohorts:", COHORTS)

Project folder exists: True
Project folder: C:\Users\LAPTOP\Downloads\luad_reserch_code
Number of cohorts: 7
Cohorts: ['TCGA_Atlas_2018', 'LUNG_MSK_2017', 'MSK_NPJPO_2021', 'MSKCC_2020', 'MSKCC_2023', 'NCI_2022', 'ONCOSG_2020']

In [16]:
# Step 2 — Locate mutation and clinical files

REQUIRED_FILENAMES = [
    "data_mutations.txt",
    "data_clinical_patient.txt",
    "data_clinical_sample.txt"
]

located_files = {}

for filename in REQUIRED_FILENAMES:
    matches = list(PROJECT_DIR.rglob(filename))
    located_files[filename] = matches

    print(f"\n{'=' * 70}")
    print(f"FILE: {filename}")
    print(f"FOUND: {len(matches)}")
    print("=" * 70)

    if matches:
        for index, path in enumerate(matches, start=1):
            print(f"{index}. {path}")
    else:
        print("No matching file found.")

======================================================================
FILE: data_mutations.txt
FOUND: 0
======================================================================
No matching file found.

======================================================================
FILE: data_clinical_patient.txt
FOUND: 0
======================================================================
No matching file found.

======================================================================
FILE: data_clinical_sample.txt
FOUND: 0
======================================================================
No matching file found.

In [17]:
# Step 3 — Search using partial filenames

search_patterns = [
    "*mutation*",
    "*clinical*",
    "*.zip"
]

for pattern in search_patterns:
    matches = [
        path for path in PROJECT_DIR.rglob(pattern)
        if path.is_file()
    ]

    print(f"\n{'=' * 80}")
    print(f"SEARCH PATTERN: {pattern}")
    print(f"FILES FOUND: {len(matches)}")
    print("=" * 80)

    if matches:
        for index, path in enumerate(matches, start=1):
            print(f"{index}. {path}")
    else:
        print("No matching files found.")

================================================================================
SEARCH PATTERN: *mutation*
FILES FOUND: 68
================================================================================
1. C:\Users\LAPTOP\Downloads\luad_reserch_code\02_mutation_features_and_position_masks.ipynb
2. C:\Users\LAPTOP\Downloads\luad_reserch_code\05_filter_mutations.py
3. C:\Users\LAPTOP\Downloads\luad_reserch_code\lung_msk_2017_data_mutations.txt
4. C:\Users\LAPTOP\Downloads\luad_reserch_code\mskcc_2020_data_mutations.txt
5. C:\Users\LAPTOP\Downloads\luad_reserch_code\mskcc_2023_data_mutations.txt
6. C:\Users\LAPTOP\Downloads\luad_reserch_code\msk_npjpo_2021_data_mutations.txt
7. C:\Users\LAPTOP\Downloads\luad_reserch_code\nci_2022_data_mutations.txt
8. C:\Users\LAPTOP\Downloads\luad_reserch_code\oncosg_2020_data_mutations.txt
9. C:\Users\LAPTOP\Downloads\luad_reserch_code\tcga_atlas_2018_data_mutations.txt
10. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sklearn\inspection\_permutation_importance.py
11. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sklearn\inspection\tests\test_permutation_importance.py
12. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sklearn\inspection\tests\__pycache__\test_permutation_importance.cpython-310.pyc
13. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sklearn\inspection\__pycache__\_permutation_importance.cpython-310.pyc
14. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\combinatorics\permutations.py
15. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\combinatorics\tests\test_permutations.py
16. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\combinatorics\tests\__pycache__\test_permutations.cpython-310.pyc
17. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\combinatorics\__pycache__\permutations.cpython-310.pyc
18. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\matrices\expressions\permutation.py
19. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\matrices\expressions\tests\test_permutation.py
20. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\matrices\expressions\tests\__pycache__\test_permutation.cpython-310.pyc
21. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\sympy\matrices\expressions\__pycache__\permutation.cpython-310.pyc
22. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\include\Eigen\src\Core\PermutationMatrix.h
23. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\include\Eigen\src\SparseCore\SparsePermutation.h
24. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\include\tensorflow\compiler\xla\permutation_util.h
25. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\include\tensorflow\core\util\permutation_input_iterator.h
26. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\include\tensorflow\core\util\permutation_output_iterator.h
27. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\include\xla\permutation_util.h
28. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\python\ops\linalg\linear_operator_permutation.py
29. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\tensorflow\python\ops\linalg\__pycache__\linear_operator_permutation.cpython-310.pyc
30. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\include\torch\csrc\jit\passes\remove_mutation.h
31. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\include\torch\csrc\jit\passes\restore_mutation.h
32. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\include\torch\csrc\lazy\core\permutation_util.h
33. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\_dynamo\mutation_guard.py
34. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\_dynamo\__pycache__\mutation_guard.cpython-310.pyc
35. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\_export\db\examples\model_attr_mutation.py
36. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\_export\db\examples\user_input_mutation.py
37. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\_export\db\examples\__pycache__\model_attr_mutation.cpython-310.pyc
38. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv\Lib\site-packages\torch\_export\db\examples\__pycache__\user_input_mutation.cpython-310.pyc
39. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sklearn\inspection\_permutation_importance.py
40. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sklearn\inspection\tests\test_permutation_importance.py
41. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sklearn\inspection\tests\__pycache__\test_permutation_importance.cpython-310.pyc
42. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sklearn\inspection\__pycache__\_permutation_importance.cpython-310.pyc
43. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\combinatorics\permutations.py
44. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\combinatorics\tests\test_permutations.py
45. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\combinatorics\tests\__pycache__\test_permutations.cpython-310.pyc
46. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\combinatorics\__pycache__\permutations.cpython-310.pyc
47. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\matrices\expressions\permutation.py
48. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\matrices\expressions\tests\test_permutation.py
49. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\matrices\expressions\tests\__pycache__\test_permutation.cpython-310.pyc
50. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\sympy\matrices\expressions\__pycache__\permutation.cpython-310.pyc
51. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\torch\include\torch\csrc\jit\passes\remove_mutation.h
52. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\torch\include\torch\csrc\jit\passes\restore_mutation.h
53. C:\Users\LAPTOP\Downloads\luad_reserch_code\.venv_dnabert\Lib\site-packages\torch\include\torch\csrc\lazy\core\permutation_util.h
54. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows.csv
55. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_qc_examples.csv
56. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_qc_examples_v2.csv
57. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_qc_examples_v3.csv
58. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_summary.txt
59. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_summary_v2.txt
60. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_summary_v3.txt
61. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_v2.csv
62. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_mutation_adjusted_windows_v3.csv
63. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_filtered_mutations.csv
64. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_filtered_mutations_all_cohorts.csv
65. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_filtered_mutations_cohort_summary.csv
66. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_filtered_mutations_summary.txt
67. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_mutations_clinical_merged.csv
68. C:\Users\LAPTOP\Downloads\luad_reserch_code\__pycache__\05_filter_mutations.cpython-310.pyc

================================================================================
SEARCH PATTERN: *clinical*
FILES FOUND: 23
================================================================================
1. C:\Users\LAPTOP\Downloads\luad_reserch_code\01_column_discovery_and_clinical_audit.ipynb
2. C:\Users\LAPTOP\Downloads\luad_reserch_code\06_merge_clinical.py
3. C:\Users\LAPTOP\Downloads\luad_reserch_code\clinical.project-tcga-luad.2026-06-19.json
4. C:\Users\LAPTOP\Downloads\luad_reserch_code\lung_msk_2017_data_clinical_patient.txt
5. C:\Users\LAPTOP\Downloads\luad_reserch_code\lung_msk_2017_data_clinical_sample.txt
6. C:\Users\LAPTOP\Downloads\luad_reserch_code\mskcc_2020_data_clinical_patient.txt
7. C:\Users\LAPTOP\Downloads\luad_reserch_code\mskcc_2020_data_clinical_sample.txt
8. C:\Users\LAPTOP\Downloads\luad_reserch_code\mskcc_2023_data_clinical_patient.txt
9. C:\Users\LAPTOP\Downloads\luad_reserch_code\mskcc_2023_data_clinical_sample.txt
10. C:\Users\LAPTOP\Downloads\luad_reserch_code\msk_npjpo_2021_data_clinical_patient.txt
11. C:\Users\LAPTOP\Downloads\luad_reserch_code\msk_npjpo_2021_data_clinical_sample.txt
12. C:\Users\LAPTOP\Downloads\luad_reserch_code\nci_2022_data_clinical_patient.txt
13. C:\Users\LAPTOP\Downloads\luad_reserch_code\nci_2022_data_clinical_sample.txt
14. C:\Users\LAPTOP\Downloads\luad_reserch_code\oncosg_2020_data_clinical_patient.txt
15. C:\Users\LAPTOP\Downloads\luad_reserch_code\oncosg_2020_data_clinical_sample.txt
16. C:\Users\LAPTOP\Downloads\luad_reserch_code\tcga_atlas_2018_data_clinical_patient.txt
17. C:\Users\LAPTOP\Downloads\luad_reserch_code\tcga_atlas_2018_data_clinical_sample.txt
18. C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processed\luad_improved_clinical_covariates.csv
19. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_clinical_labels.csv
20. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_clinical_merge_cohort_summary.csv
21. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_clinical_merge_summary.txt
22. C:\Users\LAPTOP\Downloads\luad_reserch_code\processed\LUAD_mutations_clinical_merged.csv
23. C:\Users\LAPTOP\Downloads\luad_reserch_code\__pycache__\06_merge_clinical.cpython-310.pyc

================================================================================
SEARCH PATTERN: *.zip
FILES FOUND: 0
================================================================================
No matching files found.

In [18]:
# Step 4 — Map each cohort to its exact source files

COHORT_FILE_PREFIXES = {
    "TCGA_Atlas_2018": "tcga_atlas_2018",
    "LUNG_MSK_2017": "lung_msk_2017",
    "MSK_NPJPO_2021": "msk_npjpo_2021",
    "MSKCC_2020": "mskcc_2020",
    "MSKCC_2023": "mskcc_2023",
    "NCI_2022": "nci_2022",
    "ONCOSG_2020": "oncosg_2020"
}

cohort_files = {}

for cohort, prefix in COHORT_FILE_PREFIXES.items():
    mutation_file = PROJECT_DIR / f"{prefix}_data_mutations.txt"
    patient_file = PROJECT_DIR / f"{prefix}_data_clinical_patient.txt"
    sample_file = PROJECT_DIR / f"{prefix}_data_clinical_sample.txt"

    cohort_files[cohort] = {
        "mutation": mutation_file,
        "clinical_patient": patient_file,
        "clinical_sample": sample_file
    }

    print(f"\n{cohort}")
    print("  Mutation file:", mutation_file.exists())
    print("  Patient file :", patient_file.exists())
    print("  Sample file  :", sample_file.exists())

TCGA_Atlas_2018
  Mutation file: True
  Patient file : True
  Sample file  : True

LUNG_MSK_2017
  Mutation file: True
  Patient file : True
  Sample file  : True

MSK_NPJPO_2021
  Mutation file: True
  Patient file : True
  Sample file  : True

MSKCC_2020
  Mutation file: True
  Patient file : True
  Sample file  : True

MSKCC_2023
  Mutation file: True
  Patient file : True
  Sample file  : True

NCI_2022
  Mutation file: True
  Patient file : True
  Sample file  : True

ONCOSG_2020
  Mutation file: True
  Patient file : True
  Sample file  : True

In [19]:
# Step 5 — Discover all actual column names

column_inventory = {}

for cohort, files in cohort_files.items():
    column_inventory[cohort] = {}

    print("\n" + "=" * 100)
    print("COHORT:", cohort)
    print("=" * 100)

    for file_type, file_path in files.items():
        try:
            # cBioPortal metadata rows beginning with # are ignored
            header_df = pd.read_csv(
                file_path,
                sep="\t",
                comment="#",
                nrows=0,
                encoding="utf-8"
            )

            columns = header_df.columns.tolist()
            column_inventory[cohort][file_type] = columns

            print(f"\n{file_type.upper()}")
            print(f"Number of columns: {len(columns)}")

            for column_number, column_name in enumerate(columns, start=1):
                print(f"  {column_number}. {column_name}")

        except UnicodeDecodeError:
            # Fallback for files with a different text encoding
            header_df = pd.read_csv(
                file_path,
                sep="\t",
                comment="#",
                nrows=0,
                encoding="latin-1"
            )

            columns = header_df.columns.tolist()
            column_inventory[cohort][file_type] = columns

            print(f"\n{file_type.upper()} — latin-1 encoding")
            print(f"Number of columns: {len(columns)}")

            for column_number, column_name in enumerate(columns, start=1):
                print(f"  {column_number}. {column_name}")

        except Exception as error:
            column_inventory[cohort][file_type] = []
            print(f"\n{file_type.upper()}")
            print("ERROR:", error)

====================================================================================================
COHORT: TCGA_Atlas_2018
====================================================================================================

MUTATION
Number of columns: 114
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Consequence
  10. Variant_Classification
  11. Variant_Type
  12. Reference_Allele
  13. Tumor_Seq_Allele1
  14. Tumor_Seq_Allele2
  15. dbSNP_RS
  16. dbSNP_Val_Status
  17. Tumor_Sample_Barcode
  18. Matched_Norm_Sample_Barcode
  19. Match_Norm_Seq_Allele1
  20. Match_Norm_Seq_Allele2
  21. Tumor_Validation_Allele1
  22. Tumor_Validation_Allele2
  23. Match_Norm_Validation_Allele1
  24. Match_Norm_Validation_Allele2
  25. Verification_Status
  26. Validation_Status
  27. Mutation_Status
  28. Sequencing_Phase
  29. Sequence_Source
  30. Validation_Method
  31. Score
  32. BAM_File
  33. Sequencer
  34. t_ref_count
  35. t_alt_count
  36. n_ref_count
  37. n_alt_count
  38. HGVSc
  39. HGVSp
  40. HGVSp_Short
  41. Transcript_ID
  42. RefSeq
  43. Protein_position
  44. Codons
  45. Hotspot
  46. AA_MAF
  47. AFR_MAF
  48. ALLELE_NUM
  49. AMR_MAF
  50. ASN_MAF
  51. Allele
  52. Amino_acids
  53. BIOTYPE
  54. CANONICAL
  55. CCDS
  56. CDS_position
  57. CENTERS
  58. CLIN_SIG
  59. CONTEXT
  60. COSMIC
  61. DBVS
  62. DISTANCE
  63. DOMAINS
  64. EAS_MAF
  65. EA_MAF
  66. ENSP
  67. EUR_MAF
  68. EXON
  69. ExAC_AF
  70. ExAC_AF_AFR
  71. ExAC_AF_AMR
  72. ExAC_AF_EAS
  73. ExAC_AF_FIN
  74. ExAC_AF_NFE
  75. ExAC_AF_OTH
  76. ExAC_AF_SAS
  77. Existing_variation
  78. Exon_Number
  79. FILTER
  80. Feature
  81. Feature_type
  82. GENE_PHENO
  83. GMAF
  84. Gene
  85. HGNC_ID
  86. HGVS_OFFSET
  87. HIGH_INF_POS
  88. IMPACT
  89. INTRON
  90. MERGESOURCE
  91. MINIMISED
  92. MOTIF_NAME
  93. MOTIF_POS
  94. MOTIF_SCORE_CHANGE
  95. NCALLERS
  96. PHENO
  97. PICK
  98. PUBMED
  99. PolyPhen
  100. SAS_MAF
  101. SIFT
  102. SOMATIC
  103. SWISSPROT
  104. SYMBOL
  105. SYMBOL_SOURCE
  106. TREMBL
  107. TSL
  108. UNIPARC
  109. VARIANT_CLASS
  110. all_effects
  111. cDNA_position
  112. n_depth
  113. t_depth
  114. Annotation_Status

CLINICAL_PATIENT
Number of columns: 38
  1. PATIENT_ID
  2. SUBTYPE
  3. CANCER_TYPE_ACRONYM
  4. OTHER_PATIENT_ID
  5. AGE
  6. SEX
  7. AJCC_PATHOLOGIC_TUMOR_STAGE
  8. AJCC_STAGING_EDITION
  9. DAYS_LAST_FOLLOWUP
  10. DAYS_TO_BIRTH
  11. DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS
  12. ETHNICITY
  13. FORM_COMPLETION_DATE
  14. HISTORY_NEOADJUVANT_TRTYN
  15. ICD_10
  16. ICD_O_3_HISTOLOGY
  17. ICD_O_3_SITE
  18. INFORMED_CONSENT_VERIFIED
  19. NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT
  20. PATH_M_STAGE
  21. PATH_N_STAGE
  22. PATH_T_STAGE
  23. PERSON_NEOPLASM_CANCER_STATUS
  24. PRIMARY_LYMPH_NODE_PRESENTATION_ASSESSMENT
  25. PRIOR_DX
  26. RACE
  27. RADIATION_THERAPY
  28. WEIGHT
  29. IN_PANCANPATHWAYS_FREEZE
  30. OS_STATUS
  31. OS_MONTHS
  32. DSS_STATUS
  33. DSS_MONTHS
  34. DFS_STATUS
  35. DFS_MONTHS
  36. PFS_STATUS
  37. PFS_MONTHS
  38. GENETIC_ANCESTRY_LABEL

CLINICAL_SAMPLE
Number of columns: 19
  1. PATIENT_ID
  2. SAMPLE_ID
  3. ONCOTREE_CODE
  4. CANCER_TYPE
  5. CANCER_TYPE_DETAILED
  6. TUMOR_TYPE
  7. GRADE
  8. TISSUE_PROSPECTIVE_COLLECTION_INDICATOR
  9. TISSUE_RETROSPECTIVE_COLLECTION_INDICATOR
  10. TISSUE_SOURCE_SITE_CODE
  11. TUMOR_TISSUE_SITE
  12. ANEUPLOIDY_SCORE
  13. SAMPLE_TYPE
  14. MSI_SCORE_MANTIS
  15. MSI_SENSOR_SCORE
  16. SOMATIC_STATUS
  17. TMB_NONSYNONYMOUS
  18. TISSUE_SOURCE_SITE
  19. TBL_SCORE

====================================================================================================
COHORT: LUNG_MSK_2017
====================================================================================================

MUTATION
Number of columns: 45
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Consequence
  10. Variant_Classification
  11. Variant_Type
  12. Reference_Allele
  13. Tumor_Seq_Allele1
  14. Tumor_Seq_Allele2
  15. dbSNP_RS
  16. dbSNP_Val_Status
  17. Tumor_Sample_Barcode
  18. Matched_Norm_Sample_Barcode
  19. Match_Norm_Seq_Allele1
  20. Match_Norm_Seq_Allele2
  21. Tumor_Validation_Allele1
  22. Tumor_Validation_Allele2
  23. Match_Norm_Validation_Allele1
  24. Match_Norm_Validation_Allele2
  25. Verification_Status
  26. Validation_Status
  27. Mutation_Status
  28. Sequencing_Phase
  29. Sequence_Source
  30. Validation_Method
  31. Score
  32. BAM_File
  33. Sequencer
  34. t_ref_count
  35. t_alt_count
  36. n_ref_count
  37. n_alt_count
  38. HGVSc
  39. HGVSp
  40. HGVSp_Short
  41. Transcript_ID
  42. RefSeq
  43. Protein_position
  44. Codons
  45. Hotspot

CLINICAL_PATIENT
Number of columns: 11
  1. PATIENT_ID
  2. AGE
  3. VITAL_STATUS
  4. TARGET_THERAPY
  5. IMMUNE_TREATMENT
  6. TREATMENT_CHEMOTHERAPY
  7. CLINICAL_TRIAL
  8. OVERALL_PATIENT_HISTOLOGY
  9. SMOKING_HISTORY
  10. SEX
  11. DURABLE_CLINICAL_BENEFIT

CLINICAL_SAMPLE
Number of columns: 20
  1. PATIENT_ID
  2. SAMPLE_ID
  3. SAMPLE_TYPE
  4. SAMPLE_CLASS
  5. METASTATIC_SITE
  6. PRIMARY_SITE
  7. SAMPLE_COVERAGE
  8. TUMOR_PURITY
  9. ONCOTREE_CODE
  10. CANCER_TYPE
  11. CANCER_TYPE_DETAILED
  12. INSTITUTE
  13. SOMATIC_STATUS
  14. GENE_PANEL
  15. LINES_OF_TX_PRIOR_IMPACT
  16. STAGE_AT_DIAGNOSIS
  17. DRIVER_MUTATIONS
  18. SAMPLE_PRE_LUNG_THERAPY
  19. RECURRENT_METASTATIC_DISEASE
  20. TMB_NONSYNONYMOUS

====================================================================================================
COHORT: MSK_NPJPO_2021
====================================================================================================

MUTATION
Number of columns: 124
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Consequence
  10. Variant_Classification
  11. Variant_Type
  12. Reference_Allele
  13. Tumor_Seq_Allele1
  14. Tumor_Seq_Allele2
  15. dbSNP_RS
  16. dbSNP_Val_Status
  17. Tumor_Sample_Barcode
  18. Matched_Norm_Sample_Barcode
  19. Match_Norm_Seq_Allele1
  20. Match_Norm_Seq_Allele2
  21. Tumor_Validation_Allele1
  22. Tumor_Validation_Allele2
  23. Match_Norm_Validation_Allele1
  24. Match_Norm_Validation_Allele2
  25. Verification_Status
  26. Validation_Status
  27. Mutation_Status
  28. Sequencing_Phase
  29. Sequence_Source
  30. Validation_Method
  31. Score
  32. BAM_File
  33. Sequencer
  34. t_ref_count
  35. t_alt_count
  36. n_ref_count
  37. n_alt_count
  38. HGVSc
  39. HGVSp
  40. HGVSp_Short
  41. Transcript_ID
  42. RefSeq
  43. Protein_position
  44. Codons
  45. Hotspot
  46. AA_MAF
  47. AFR_MAF
  48. ALLELE_NUM
  49. AMR_MAF
  50. ASN_MAF
  51. Allele
  52. Amino_Acid_Change
  53. Amino_acids
  54. BIOTYPE
  55. CANONICAL
  56. CCDS
  57. CDS_position
  58. CLIN_SIG
  59. COMMENTS
  60. Comments
  61. DISTANCE
  62. DOMAINS
  63. EAS_MAF
  64. EA_MAF
  65. ENSP
  66. EUR_MAF
  67. EXON
  68. ExAC_AF
  69. ExAC_AF_AFR
  70. ExAC_AF_AMR
  71. ExAC_AF_EAS
  72. ExAC_AF_FIN
  73. ExAC_AF_NFE
  74. ExAC_AF_OTH
  75. ExAC_AF_SAS
  76. Existing_variation
  77. Exon_Number
  78. FILTER
  79. Feature
  80. Feature_type
  81. GENE_PHENO
  82. GMAF
  83. Gene
  84. HGNC_ID
  85. HGVS_OFFSET
  86. HIGH_INF_POS
  87. IMPACT
  88. INTRON
  89. IS_NEW
  90. MA:FIS
  91. MA:FImpact
  92. MA:link.MSA
  93. MA:link.PDB
  94. MA:link.var
  95. MA:protein.change
  96. MINIMISED
  97. MOTIF_NAME
  98. MOTIF_POS
  99. MOTIF_SCORE_CHANGE
  100. PHENO
  101. PICK
  102. PUBMED
  103. PolyPhen
  104. SAS_MAF
  105. SIFT
  106. SOMATIC
  107. SWISSPROT
  108. SYMBOL
  109. SYMBOL_SOURCE
  110. TREMBL
  111. TSL
  112. Transcript
  113. UNIPARC
  114. VARIANT_CLASS
  115. all_effects
  116. amino_acid_change
  117. cDNA_Change
  118. cDNA_position
  119. cdna_change
  120. comments
  121. n_depth
  122. t_depth
  123. transcript
  124. Annotation_Status

CLINICAL_PATIENT
Number of columns: 13
  1. PATIENT_ID
  2. AGE_AT_RESECTION
  3. SEX
  4. SMOKING_STATUS
  5. SMOKING_PACK_YEARS
  6. TUMOR_MORPHOLOGIC_APPEARANCE_ON_CT
  7. TUMOR_SIZE_ON_CT
  8. TUMOR_SUVMAX
  9. CLIN_N_STAGE_CODE
  10. CLINICAL_STAGE
  11. BIOPSY_CONTAINS_MIP
  12. BIOPSY_CONTAINS_SOLID
  13. LN_STATUS

CLINICAL_SAMPLE
Number of columns: 5
  1. PATIENT_ID
  2. SAMPLE_ID
  3. FGA_FACETS
  4. WGD
  5. TMB_NONSYNONYMOUS

====================================================================================================
COHORT: MSKCC_2020
====================================================================================================

MUTATION
Number of columns: 123
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Variant_Classification
  10. Variant_Type
  11. Reference_Allele
  12. Tumor_Seq_Allele1
  13. Tumor_Seq_Allele2
  14. dbSNP_RS
  15. dbSNP_Val_Status
  16. Tumor_Sample_Barcode
  17. Matched_Norm_Sample_Barcode
  18. Match_Norm_Seq_Allele1
  19. Match_Norm_Seq_Allele2
  20. Tumor_Validation_Allele1
  21. Tumor_Validation_Allele2
  22. Match_Norm_Validation_Allele1
  23. Match_Norm_Validation_Allele2
  24. Verification_Status
  25. Validation_Status
  26. Mutation_Status
  27. Sequencing_Phase
  28. Sequence_Source
  29. Validation_Method
  30. Score
  31. BAM_File
  32. Sequencer
  33. t_ref_count
  34. t_alt_count
  35. n_ref_count
  36. n_alt_count
  37. COMMENTS
  38. Consequence
  39. HGVSc
  40. HGVSp
  41. HGVSp_Short
  42. Transcript_ID
  43. RefSeq
  44. Protein_position
  45. Codons
  46. Hotspot
  47. AA_MAF
  48. AFR_MAF
  49. ALLELE_NUM
  50. AMR_MAF
  51. ASN_MAF
  52. Allele
  53. Amino_Acid_Change
  54. Amino_acids
  55. BIOTYPE
  56. CANONICAL
  57. CCDS
  58. CDS_position
  59. CLIN_SIG
  60. Comments
  61. DISTANCE
  62. DOMAINS
  63. EAS_MAF
  64. EA_MAF
  65. ENSP
  66. EUR_MAF
  67. EXON
  68. ExAC_AF
  69. ExAC_AF_AFR
  70. ExAC_AF_AMR
  71. ExAC_AF_EAS
  72. ExAC_AF_FIN
  73. ExAC_AF_NFE
  74. ExAC_AF_OTH
  75. ExAC_AF_SAS
  76. Existing_variation
  77. Exon_Number
  78. FILTER
  79. Feature
  80. Feature_type
  81. GENE_PHENO
  82. GMAF
  83. Gene
  84. HGNC_ID
  85. HGVS_OFFSET
  86. HIGH_INF_POS
  87. IMPACT
  88. INTRON
  89. IS_NEW
  90. MA:FIS
  91. MA:FImpact
  92. MA:link.MSA
  93. MA:link.PDB
  94. MA:link.var
  95. MA:protein.change
  96. MINIMISED
  97. MOTIF_NAME
  98. MOTIF_POS
  99. MOTIF_SCORE_CHANGE
  100. PHENO
  101. PICK
  102. PUBMED
  103. PolyPhen
  104. SAS_MAF
  105. SIFT
  106. SOMATIC
  107. SWISSPROT
  108. SYMBOL
  109. SYMBOL_SOURCE
  110. TREMBL
  111. TSL
  112. Transcript
  113. UNIPARC
  114. VARIANT_CLASS
  115. all_effects
  116. amino_acid_change
  117. cDNA_Change
  118. cDNA_position
  119. cdna_change
  120. comments
  121. n_depth
  122. t_depth
  123. transcript

CLINICAL_PATIENT
Number of columns: 14
  1. PATIENT_ID
  2. SEX
  3. AGE_AT_SURGERY
  4. SMOKING_HISTORY
  5. SMOKING_PACK_YEARS
  6. SUV
  7. CT_SIZE
  8. CN_STATUS
  9. DLCO
  10. FEV1
  11. RFS_STATUS
  12. RFS_MONTHS
  13. OS_MONTHS
  14. OS_STATUS

CLINICAL_SAMPLE
Number of columns: 12
  1. SAMPLE_ID
  2. PATIENT_ID
  3. PN_STATUS
  4. PATHOLOGIC_STAGE
  5. SUBTYPE_GROUP
  6. PREDOMINANT_HISTOLOGIC_SUBTYPE
  7. FGA_FACETS
  8. TMB
  9. ONCOTREE_CODE
  10. CANCER_TYPE
  11. CANCER_TYPE_DETAILED
  12. TMB_NONSYNONYMOUS

====================================================================================================
COHORT: MSKCC_2023
====================================================================================================

MUTATION
Number of columns: 123
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Consequence
  10. Variant_Classification
  11. Variant_Type
  12. Reference_Allele
  13. Tumor_Seq_Allele1
  14. Tumor_Seq_Allele2
  15. dbSNP_RS
  16. dbSNP_Val_Status
  17. Tumor_Sample_Barcode
  18. Matched_Norm_Sample_Barcode
  19. Match_Norm_Seq_Allele1
  20. Match_Norm_Seq_Allele2
  21. Tumor_Validation_Allele1
  22. Tumor_Validation_Allele2
  23. Match_Norm_Validation_Allele1
  24. Match_Norm_Validation_Allele2
  25. Verification_Status
  26. Validation_Status
  27. Mutation_Status
  28. Sequencing_Phase
  29. Sequence_Source
  30. Validation_Method
  31. Score
  32. BAM_File
  33. Sequencer
  34. t_ref_count
  35. t_alt_count
  36. n_ref_count
  37. n_alt_count
  38. HGVSc
  39. HGVSp
  40. HGVSp_Short
  41. Transcript_ID
  42. RefSeq
  43. Protein_position
  44. Codons
  45. Exon_Number
  46. AA_MAF
  47. AFR_MAF
  48. ALLELE_NUM
  49. AMR_MAF
  50. ASN_MAF
  51. Allele
  52. Amino_Acid_Change
  53. Amino_acids
  54. BIOTYPE
  55. CANONICAL
  56. CCDS
  57. CDS_position
  58. CLIN_SIG
  59. COMMENTS
  60. Comments
  61. DISTANCE
  62. DOMAINS
  63. EAS_MAF
  64. EA_MAF
  65. ENSP
  66. EUR_MAF
  67. EXON
  68. ExAC_AF
  69. ExAC_AF_AFR
  70. ExAC_AF_AMR
  71. ExAC_AF_EAS
  72. ExAC_AF_FIN
  73. ExAC_AF_NFE
  74. ExAC_AF_OTH
  75. ExAC_AF_SAS
  76. Existing_variation
  77. FILTER
  78. Feature
  79. Feature_type
  80. GENE_PHENO
  81. GMAF
  82. Gene
  83. HGNC_ID
  84. HGVS_OFFSET
  85. HIGH_INF_POS
  86. IMPACT
  87. INTRON
  88. IS_NEW
  89. MA:FIS
  90. MA:FImpact
  91. MA:link.MSA
  92. MA:link.PDB
  93. MA:link.var
  94. MA:protein.change
  95. MINIMISED
  96. MOTIF_NAME
  97. MOTIF_POS
  98. MOTIF_SCORE_CHANGE
  99. PHENO
  100. PICK
  101. PUBMED
  102. PolyPhen
  103. SAS_MAF
  104. SIFT
  105. SOMATIC
  106. SWISSPROT
  107. SYMBOL
  108. SYMBOL_SOURCE
  109. TREMBL
  110. TSL
  111. Transcript
  112. UNIPARC
  113. VARIANT_CLASS
  114. all_effects
  115. amino_acid_change
  116. cDNA_Change
  117. cDNA_position
  118. cdna_change
  119. comments
  120. n_depth
  121. t_depth
  122. transcript
  123. Annotation_Status

CLINICAL_PATIENT
Number of columns: 32
  1. PATIENT_ID
  2. RACE
  3. SEX
  4. OS_STATUS
  5. OS_MONTHS
  6. HAD_SURGERY
  7. CIGARETTE_HX
  8. NEOADJUVANT
  9. NEOADJUVANT_CHEMOTHERAPY
  10. NEOADJUVANT_IMMUNOTHERAPY
  11. NEOADJUVANT_TARGETED
  12. NEOADJUVANT_XRT
  13. ADJUVANT
  14. ADJUVANT_CHEMOTHERAPY
  15. ADJUVANT_IMMUNOTHERAPY
  16. ADJUVANT_TARGETED
  17. ADJUVANT_XRT
  18. ADRENAL_STATUS
  19. ADRENAL_MONTHS
  20. BONE_STATUS
  21. BONE_MONTHS
  22. CNS_STATUS
  23. CNS_MONTHS
  24. LIVER_STATUS
  25. LIVER_MONTHS
  26. LN_STATUS
  27. LN_MONTHS
  28. LUNG_STATUS
  29. LUNG_MONTHS
  30. PLEURA_STATUS
  31. PLEURA_MONTHS
  32. MONTHS_FROM_MATCHED_PRIM

CLINICAL_SAMPLE
Number of columns: 59
  1. SAMPLE_ID
  2. PATIENT_ID
  3. CANCER_TYPE
  4. SAMPLE_TYPE
  5. SAMPLE_CLASS
  6. METASTATIC_SITE
  7. PRIMARY_SITE
  8. CANCER_TYPE_DETAILED
  9. GENE_PANEL
  10. SAMPLE_COVERAGE
  11. ONCOTREE_CODE
  12. MSI_SCORE
  13. MSI_TYPE
  14. INSTITUTE
  15. SOMATIC_STATUS
  16. GROUP_NO
  17. IMPACT_PRIMARY_GROUP
  18. IMPACT_METASTATIC_LESION
  19. IN_MATCHED
  20. FU_2YRS
  21. AGE_AT_DOS_BX
  22. PREDOM_HISTO_SUBTYPE
  23. CSTAGE
  24. PSTAGE
  25. ADJUVANT_THERAPY
  26. PRE_SAMPLE_CHEMOTHERAPY
  27. PRE_SAMPLE_IMMUNOTHERAPY
  28. PRE_SAMPLE_TARGETED
  29. PRE_SAMPLE_XRT
  30. PRE_SAMPLE_TX
  31. POST_SAMPLE_CHEMOTHERAPY
  32. POST_SAMPLE_IMMUNOTHERAPY
  33. POST_SAMPLE_TARGETED
  34. POST_SAMPLE_XRT
  35. POST_SAMPLE_TX
  36. METASTATIC_BURDEN
  37. EVER_MET_SITE_ADRENAL
  38. EVER_MET_SITE_BONE
  39. EVER_MET_SITE_CNS
  40. EVER_MET_SITE_LIVER_BILIARY_TRACT
  41. EVER_MET_SITE_LN
  42. EVER_MET_SITE_LUNG
  43. EVER_MET_SITE_PLEURA
  44. DEATH
  45. FGA
  46. IS_WGD
  47. PLOIDY
  48. PURITY
  49. CELL_CYCLE
  50. MYC_PATH
  51. TGF_BETA
  52. RTK_RAS
  53. TP53_PATH
  54. HIPPO
  55. NOTCH
  56. NRF2
  57. PI3K
  58. WNT
  59. TMB_NONSYNONYMOUS

====================================================================================================
COHORT: NCI_2022
====================================================================================================

MUTATION
Number of columns: 60
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Consequence
  10. Variant_Classification
  11. Variant_Type
  12. Reference_Allele
  13. Tumor_Seq_Allele1
  14. Tumor_Seq_Allele2
  15. dbSNP_RS
  16. dbSNP_Val_Status
  17. Tumor_Sample_Barcode
  18. Matched_Norm_Sample_Barcode
  19. Mutation_Status
  20. HGVSc
  21. HGVSp
  22. HGVSp_Short
  23. Transcript_ID
  24. RefSeq
  25. Protein_position
  26. Codons
  27. Hotspot
  28. ACMG_Classification
  29. AF
  30. AF_Exomes
  31. AF_Genomes
  32. CCF
  33. Cancer_Gene
  34. CharGer_Classification
  35. CharGer_Score
  36. CharGer_Summary
  37. ClinVar_Pathogenicity
  38. ClinVar_Traits
  39. Clone
  40. Gene_Germline_Freq
  41. GtypeCount
  42. ID1
  43. ID2
  44. MutCount
  45. Negative_CharGer_Score
  46. Negative_Evidence
  47. Normal_MPG/Coverage_ratio
  48. Normal_MPG_score
  49. Normal_coverage
  50. PanCancer_Driver_Gene
  51. Positive_CharGer_Score
  52. Positive_Evidence
  53. PubMed_Link
  54. SCNA_Cluster
  55. Sherlock_Driver_Gene
  56. Somatic_Drivers
  57. Somatic_LOH
  58. Somatic_Variant_Classification
  59. VCF_Variant
  60. mutationID

CLINICAL_PATIENT
Number of columns: 9
  1. PATIENT_ID
  2. SEX
  3. AGE
  4. TUMOR_STAGE
  5. TUMOR_GRADE
  6. PASSIVE_SMOKING
  7. OS_STATUS
  8. OS_MONTHS
  9. HISTOLOGY

CLINICAL_SAMPLE
Number of columns: 16
  1. PATIENT_ID
  2. SAMPLE_ID
  3. ONCOTREE_CODE
  4. CANCER_TYPE
  5. CANCER_TYPE_DETAILED
  6. SOMATIC_STATUS
  7. TISSUE_SOURCE_SITE
  8. MEAN_TARGET_COVERAGE_TUMOR
  9. MEAN_TARGET_COVERAGE_NORMAL
  10. TUMOR_PURITY
  11. TUMOR_PLOIDY
  12. NRPCC
  13. MUTS_SUBCLONAL_RATIO
  14. SCNA_CLUSTER
  15. HLA_LOH
  16. TMB_NONSYNONYMOUS

====================================================================================================
COHORT: ONCOSG_2020
====================================================================================================

MUTATION
Number of columns: 46
  1. Hugo_Symbol
  2. Entrez_Gene_Id
  3. Center
  4. NCBI_Build
  5. Chromosome
  6. Start_Position
  7. End_Position
  8. Strand
  9. Consequence
  10. Variant_Classification
  11. Variant_Type
  12. Reference_Allele
  13. Tumor_Seq_Allele1
  14. Tumor_Seq_Allele2
  15. dbSNP_RS
  16. dbSNP_Val_Status
  17. Tumor_Sample_Barcode
  18. Matched_Norm_Sample_Barcode
  19. Match_Norm_Seq_Allele1
  20. Match_Norm_Seq_Allele2
  21. Tumor_Validation_Allele1
  22. Tumor_Validation_Allele2
  23. Match_Norm_Validation_Allele1
  24. Match_Norm_Validation_Allele2
  25. Verification_Status
  26. Validation_Status
  27. Mutation_Status
  28. Sequencing_Phase
  29. Sequence_Source
  30. Validation_Method
  31. Score
  32. BAM_File
  33. Sequencer
  34. t_ref_count
  35. t_alt_count
  36. n_ref_count
  37. n_alt_count
  38. HGVSc
  39. HGVSp
  40. HGVSp_Short
  41. Transcript_ID
  42. RefSeq
  43. Protein_position
  44. Codons
  45. Hotspot
  46. Amino_acid_change

CLINICAL_PATIENT
Number of columns: 17
  1. PATIENT_ID
  2. COHORT
  3. OS_STATUS
  4. OS_MONTHS
  5. AGE
  6. SEX
  7. ETHNICITY
  8. SMOKING_STATUS
  9. STAGE
  10. HISTOLOGICAL_GRADE
  11. SMOKING_PACK_YEARS
  12. ADENOCARCINOMA_SUBTYPE_WHO2015
  13. TKI_TREATMENT
  14. CHEMOTHERAPY
  15. EXOME_SEQ
  16. RNA_SEQ_ANALYSIS
  17. SEQUENCING_TYPE

CLINICAL_SAMPLE
Number of columns: 20
  1. PATIENT_ID
  2. SAMPLE_ID
  3. PURITY
  4. IMSIG_B_CELLS
  5. IMSIG_INTERFERON
  6. IMSIG_MACROPHAGES
  7. IMSIG_MONOCYTES
  8. IMSIG_NEUTROPHILS
  9. IMSIG_NK_CELLS
  10. IMSIG_PLASMA_CELLS
  11. IMSIG_PROLIFERATION
  12. IMSIG_T_CELLS
  13. IMSIG_TRANSLATION
  14. SAMPLE_TYPE_ID
  15. SAMPLE_CLASS
  16. SOMATIC_STATUS
  17. ONCOTREE_CODE
  18. CANCER_TYPE
  19. CANCER_TYPE_DETAILED
  20. TMB_NONSYNONYMOUS

In [20]:
# Step 6 — Map cohort-specific clinical columns to standard fields

CLINICAL_FIELD_MAP = {
    "TCGA_Atlas_2018": {
        "age": ("clinical_patient", "AGE"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": None,
        "smoking_pack_years": None,
        "passive_smoking": None
    },

    "LUNG_MSK_2017": {
        "age": ("clinical_patient", "AGE"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": ("clinical_patient", "SMOKING_HISTORY"),
        "smoking_pack_years": None,
        "passive_smoking": None
    },

    "MSK_NPJPO_2021": {
        "age": ("clinical_patient", "AGE_AT_RESECTION"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": ("clinical_patient", "SMOKING_STATUS"),
        "smoking_pack_years": (
            "clinical_patient",
            "SMOKING_PACK_YEARS"
        ),
        "passive_smoking": None
    },

    "MSKCC_2020": {
        "age": ("clinical_patient", "AGE_AT_SURGERY"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": ("clinical_patient", "SMOKING_HISTORY"),
        "smoking_pack_years": (
            "clinical_patient",
            "SMOKING_PACK_YEARS"
        ),
        "passive_smoking": None
    },

    "MSKCC_2023": {
        "age": ("clinical_sample", "AGE_AT_DOS_BX"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": ("clinical_patient", "CIGARETTE_HX"),
        "smoking_pack_years": None,
        "passive_smoking": None
    },

    "NCI_2022": {
        "age": ("clinical_patient", "AGE"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": None,
        "smoking_pack_years": None,
        "passive_smoking": (
            "clinical_patient",
            "PASSIVE_SMOKING"
        )
    },

    "ONCOSG_2020": {
        "age": ("clinical_patient", "AGE"),
        "sex": ("clinical_patient", "SEX"),
        "smoking_status": ("clinical_patient", "SMOKING_STATUS"),
        "smoking_pack_years": (
            "clinical_patient",
            "SMOKING_PACK_YEARS"
        ),
        "passive_smoking": None
    }
}


MUTATION_FIELD_MAP = {
    cohort: {
        "gene": "Hugo_Symbol",
        "sample_id": "Tumor_Sample_Barcode",
        "variant_classification": "Variant_Classification",
        "variant_type": "Variant_Type",
        "start_position": "Start_Position",
        "end_position": "End_Position",
        "reference_allele": "Reference_Allele",
        "alternate_allele": "Tumor_Seq_Allele2",
        "hgvs_c": "HGVSc",
        "transcript_id": "Transcript_ID"
    }
    for cohort in COHORTS
}


for cohort in COHORTS:
    print(f"\n{cohort}")

    for standard_field, mapping in CLINICAL_FIELD_MAP[cohort].items():
        if mapping is None:
            print(f"  {standard_field}: NOT AVAILABLE")
        else:
            file_type, source_column = mapping
            print(
                f"  {standard_field}: "
                f"{file_type} → {source_column}"
            )

TCGA_Atlas_2018
  age: clinical_patient → AGE
  sex: clinical_patient → SEX
  smoking_status: NOT AVAILABLE
  smoking_pack_years: NOT AVAILABLE
  passive_smoking: NOT AVAILABLE

LUNG_MSK_2017
  age: clinical_patient → AGE
  sex: clinical_patient → SEX
  smoking_status: clinical_patient → SMOKING_HISTORY
  smoking_pack_years: NOT AVAILABLE
  passive_smoking: NOT AVAILABLE

MSK_NPJPO_2021
  age: clinical_patient → AGE_AT_RESECTION
  sex: clinical_patient → SEX
  smoking_status: clinical_patient → SMOKING_STATUS
  smoking_pack_years: clinical_patient → SMOKING_PACK_YEARS
  passive_smoking: NOT AVAILABLE

MSKCC_2020
  age: clinical_patient → AGE_AT_SURGERY
  sex: clinical_patient → SEX
  smoking_status: clinical_patient → SMOKING_HISTORY
  smoking_pack_years: clinical_patient → SMOKING_PACK_YEARS
  passive_smoking: NOT AVAILABLE

MSKCC_2023
  age: clinical_sample → AGE_AT_DOS_BX
  sex: clinical_patient → SEX
  smoking_status: clinical_patient → CIGARETTE_HX
  smoking_pack_years: NOT AVAILABLE
  passive_smoking: NOT AVAILABLE

NCI_2022
  age: clinical_patient → AGE
  sex: clinical_patient → SEX
  smoking_status: NOT AVAILABLE
  smoking_pack_years: NOT AVAILABLE
  passive_smoking: clinical_patient → PASSIVE_SMOKING

ONCOSG_2020
  age: clinical_patient → AGE
  sex: clinical_patient → SEX
  smoking_status: clinical_patient → SMOKING_STATUS
  smoking_pack_years: clinical_patient → SMOKING_PACK_YEARS
  passive_smoking: NOT AVAILABLE

In [21]:
# Step 7 — Load mapped clinical fields and inspect raw values

def read_cbioportal_file(file_path):
    """Read a cBioPortal text file while ignoring metadata lines."""
    return pd.read_csv(
        file_path,
        sep="\t",
        comment="#",
        dtype=str,
        low_memory=False,
        encoding="utf-8"
    )


def first_non_missing(series):
    """Return the first real value for patients with multiple samples."""
    cleaned = series.dropna().astype(str).str.strip()
    cleaned = cleaned[
        ~cleaned.str.lower().isin(
            ["", "nan", "na", "n/a", "null", "unknown", "not available"]
        )
    ]

    return cleaned.iloc[0] if len(cleaned) > 0 else np.nan


clinical_raw_tables = {}
clinical_audit_rows = []

for cohort in COHORTS:
    patient_df = read_cbioportal_file(
        cohort_files[cohort]["clinical_patient"]
    )

    sample_df = read_cbioportal_file(
        cohort_files[cohort]["clinical_sample"]
    )

    # Start with one row per patient
    clinical_df = patient_df[["PATIENT_ID"]].drop_duplicates().copy()
    clinical_df["COHORT"] = cohort

    for standard_field, mapping in CLINICAL_FIELD_MAP[cohort].items():

        if mapping is None:
            clinical_df[standard_field] = np.nan
            continue

        source_file, source_column = mapping

        if source_file == "clinical_patient":
            source_df = patient_df[["PATIENT_ID", source_column]].copy()
            source_df = source_df.drop_duplicates("PATIENT_ID")

        else:
            source_df = (
                sample_df[["PATIENT_ID", source_column]]
                .groupby("PATIENT_ID", as_index=False)
                .agg({source_column: first_non_missing})
            )

        source_df = source_df.rename(
            columns={source_column: standard_field}
        )

        clinical_df = clinical_df.merge(
            source_df,
            on="PATIENT_ID",
            how="left"
        )

    clinical_raw_tables[cohort] = clinical_df

    patient_count = len(clinical_df)

    def coverage_percent(column):
        return round(
            clinical_df[column].notna().mean() * 100,
            2
        )

    clinical_audit_rows.append(
        {
            "COHORT": cohort,
            "PATIENTS": patient_count,
            "AGE_AVAILABLE_%": coverage_percent("age"),
            "SEX_AVAILABLE_%": coverage_percent("sex"),
            "SMOKING_AVAILABLE_%": coverage_percent(
                "smoking_status"
            ),
            "PACK_YEARS_AVAILABLE_%": coverage_percent(
                "smoking_pack_years"
            ),
            "PASSIVE_SMOKING_AVAILABLE_%": coverage_percent(
                "passive_smoking"
            )
        }
    )

    print("\n" + "=" * 90)
    print("COHORT:", cohort)
    print("Clinical patients:", patient_count)
    print("=" * 90)

    print("\nRaw age examples:")
    print(
        clinical_df["age"]
        .dropna()
        .astype(str)
        .value_counts()
        .head(10)
    )

    print("\nRaw smoking-status values:")
    print(
        clinical_df["smoking_status"]
        .fillna("MISSING")
        .astype(str)
        .value_counts()
        .head(15)
    )

    print("\nRaw passive-smoking values:")
    print(
        clinical_df["passive_smoking"]
        .fillna("MISSING")
        .astype(str)
        .value_counts()
        .head(10)
    )


clinical_coverage_table = pd.DataFrame(clinical_audit_rows)

print("\n\nCLINICAL COVERAGE SUMMARY")
display(clinical_coverage_table)

==========================================================================================
COHORT: TCGA_Atlas_2018
Clinical patients: 566
==========================================================================================

Raw age examples:
age
70    26
72    22
60    21
59    21
61    21
69    20
71    19
74    19
65    18
67    17
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
MISSING    566
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
MISSING    566
Name: count, dtype: int64

==========================================================================================
COHORT: LUNG_MSK_2017
Clinical patients: 860
==========================================================================================

Raw age examples:
age
64    34
58    33
63    33
66    31
68    30
60    29
67    29
65    28
75    27
70    26
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
Former heavy     420
Never            277
Former light     153
Current heavy     10
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
MISSING    860
Name: count, dtype: int64

==========================================================================================
COHORT: MSK_NPJPO_2021
Clinical patients: 426
==========================================================================================

Raw age examples:
age
70    24
73    24
71    21
72    21
66    20
65    20
75    20
69    19
64    18
67    17
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
Ever Smoker     316
Never Smoker    110
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
MISSING    426
Name: count, dtype: int64

==========================================================================================
COHORT: MSKCC_2020
Clinical patients: 604
==========================================================================================

Raw age examples:
age
73    33
65    32
66    31
70    30
71    30
68    25
75    24
74    23
69    23
63    23
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
Ever Smoker     466
Never Smoker    138
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
MISSING    604
Name: count, dtype: int64

==========================================================================================
COHORT: MSKCC_2023
Clinical patients: 2201
==========================================================================================

Raw age examples:
age
72.30684932    4
81.61917808    3
65.10958904    3
66.22465753    3
63.3260274     3
68.66027397    3
71.82739726    3
66.50410959    3
74.71506849    3
66.28219178    3
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
MISSING    1435
Ever        550
Never       216
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
MISSING    2201
Name: count, dtype: int64

==========================================================================================
COHORT: NCI_2022
Clinical patients: 232
==========================================================================================

Raw age examples:
age
69    11
72    10
68    10
73     9
77     9
71     8
66     7
74     7
67     7
65     7
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
MISSING    232
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
No         149
Yes         64
MISSING     19
Name: count, dtype: int64

==========================================================================================
COHORT: ONCOSG_2020
Clinical patients: 305
==========================================================================================

Raw age examples:
age
67    17
72    15
68    14
70    14
62    13
63    12
57    11
60    10
66    10
58    10
Name: count, dtype: int64

Raw smoking-status values:
smoking_status
No         189
Yes        112
MISSING      4
Name: count, dtype: int64

Raw passive-smoking values:
passive_smoking
MISSING    305
Name: count, dtype: int64


CLINICAL COVERAGE SUMMARY

,COHORT,PATIENTS,AGE_AVAILABLE_%,SEX_AVAILABLE_%,SMOKING_AVAILABLE_%,PACK_YEARS_AVAILABLE_%,PASSIVE_SMOKING_AVAILABLE_%
0,TCGA_Atlas_2018,566,87.46,90.81,0.00,0.00,0.00
1,LUNG_MSK_2017,860,100.00,100.00,100.00,0.00,0.00
2,MSK_NPJPO_2021,426,100.00,100.00,100.00,99.77,0.00
3,MSKCC_2020,604,100.00,100.00,100.00,99.83,0.00
4,MSKCC_2023,2201,100.00,100.00,34.80,0.00,0.00
5,NCI_2022,232,91.81,100.00,0.00,0.00,91.81
6,ONCOSG_2020,305,100.00,100.00,98.69,25.25,0.00

In [22]:
# Step 8 — Inspect exact age and smoking values before standardization

for cohort in COHORTS:
    clinical_df = clinical_raw_tables[cohort]

    print("\n" + "=" * 90)
    print("COHORT:", cohort)
    print("=" * 90)

    # Age numeric audit
    age_numeric = pd.to_numeric(
        clinical_df["age"],
        errors="coerce"
    )

    print("\nAGE SUMMARY")
    print("Non-missing raw age:", clinical_df["age"].notna().sum())
    print("Valid numeric age  :", age_numeric.notna().sum())

    if age_numeric.notna().any():
        print("Minimum age        :", age_numeric.min())
        print("Maximum age        :", age_numeric.max())
        print("Median age         :", age_numeric.median())

    print("\nSMOKING STATUS — EXACT RAW VALUES")
    smoking_values = (
        clinical_df["smoking_status"]
        .dropna()
        .astype(str)
        .str.strip()
        .value_counts(dropna=False)
    )

    if len(smoking_values) == 0:
        print("Not available")
    else:
        print(smoking_values.to_string())

    print("\nPASSIVE SMOKING — EXACT RAW VALUES")
    passive_values = (
        clinical_df["passive_smoking"]
        .dropna()
        .astype(str)
        .str.strip()
        .value_counts(dropna=False)
    )

    if len(passive_values) == 0:
        print("Not available")
    else:
        print(passive_values.to_string())

==========================================================================================
COHORT: TCGA_Atlas_2018
==========================================================================================

AGE SUMMARY
Non-missing raw age: 495
Valid numeric age  : 495
Minimum age        : 33.0
Maximum age        : 88.0
Median age         : 66.0

SMOKING STATUS — EXACT RAW VALUES
Not available

PASSIVE SMOKING — EXACT RAW VALUES
Not available

==========================================================================================
COHORT: LUNG_MSK_2017
==========================================================================================

AGE SUMMARY
Non-missing raw age: 860
Valid numeric age  : 860
Minimum age        : 9
Maximum age        : 93
Median age         : 64.0

SMOKING STATUS — EXACT RAW VALUES
smoking_status
Former heavy     420
Never            277
Former light     153
Current heavy     10

PASSIVE SMOKING — EXACT RAW VALUES
Not available

==========================================================================================
COHORT: MSK_NPJPO_2021
==========================================================================================

AGE SUMMARY
Non-missing raw age: 426
Valid numeric age  : 426
Minimum age        : 41
Maximum age        : 87
Median age         : 69.0

SMOKING STATUS — EXACT RAW VALUES
smoking_status
Ever Smoker     316
Never Smoker    110

PASSIVE SMOKING — EXACT RAW VALUES
Not available

==========================================================================================
COHORT: MSKCC_2020
==========================================================================================

AGE SUMMARY
Non-missing raw age: 604
Valid numeric age  : 604
Minimum age        : 34
Maximum age        : 89
Median age         : 68.0

SMOKING STATUS — EXACT RAW VALUES
smoking_status
Ever Smoker     466
Never Smoker    138

PASSIVE SMOKING — EXACT RAW VALUES
Not available

==========================================================================================
COHORT: MSKCC_2023
==========================================================================================

AGE SUMMARY
Non-missing raw age: 2201
Valid numeric age  : 2201
Minimum age        : 18.56712329
Maximum age        : 97.06027397
Median age         : 66.84657534

SMOKING STATUS — EXACT RAW VALUES
smoking_status
Ever     550
Never    216

PASSIVE SMOKING — EXACT RAW VALUES
Not available

==========================================================================================
COHORT: NCI_2022
==========================================================================================

AGE SUMMARY
Non-missing raw age: 213
Valid numeric age  : 213
Minimum age        : 21.0
Maximum age        : 86.0
Median age         : 68.0

SMOKING STATUS — EXACT RAW VALUES
Not available

PASSIVE SMOKING — EXACT RAW VALUES
passive_smoking
No     149
Yes     64

==========================================================================================
COHORT: ONCOSG_2020
==========================================================================================

AGE SUMMARY
Non-missing raw age: 305
Valid numeric age  : 305
Minimum age        : 25
Maximum age        : 84
Median age         : 64.0

SMOKING STATUS — EXACT RAW VALUES
smoking_status
No     189
Yes    112

PASSIVE SMOKING — EXACT RAW VALUES
Not available

In [23]:
# Step 9 — Standardize age, smoking and passive-smoking values

def standardize_smoking_detail(value):
    if pd.isna(value):
        return "Unknown"

    value = str(value).strip().lower()

    smoking_map = {
        "never": "Never",
        "never smoker": "Never",
        "no": "Never",

        "former heavy": "Former",
        "former light": "Former",

        "current heavy": "Current",

        "ever smoker": "Ever_Unspecified",
        "ever": "Ever_Unspecified",
        "yes": "Ever_Unspecified"
    }

    return smoking_map.get(value, "Unknown")


def smoking_detail_to_binary(value):
    if value == "Never":
        return "Never"

    if value in ["Former", "Current", "Ever_Unspecified"]:
        return "Ever"

    return "Unknown"


def standardize_passive_smoking(value):
    if pd.isna(value):
        return "Unknown"

    value = str(value).strip().lower()

    if value == "yes":
        return "Yes"
    elif value == "no":
        return "No"

    return "Unknown"


standardized_clinical_tables = {}

for cohort, clinical_df in clinical_raw_tables.items():
    standardized_df = clinical_df.copy()

    # Convert age to numeric but preserve missing values
    standardized_df["age_numeric"] = pd.to_numeric(
        standardized_df["age"],
        errors="coerce"
    )

    # Flag suspicious ages without deleting them
    standardized_df["age_outlier_flag"] = (
        (standardized_df["age_numeric"] < 18)
        | (standardized_df["age_numeric"] > 100)
    ).astype(int)

    standardized_df["age_missing_flag"] = (
        standardized_df["age_numeric"].isna()
    ).astype(int)

    # Standard smoking fields
    standardized_df["smoking_detail"] = (
        standardized_df["smoking_status"]
        .apply(standardize_smoking_detail)
    )

    standardized_df["smoking_binary"] = (
        standardized_df["smoking_detail"]
        .apply(smoking_detail_to_binary)
    )

    standardized_df["passive_smoking_standardized"] = (
        standardized_df["passive_smoking"]
        .apply(standardize_passive_smoking)
    )

    standardized_clinical_tables[cohort] = standardized_df

    print("\n" + "=" * 80)
    print("COHORT:", cohort)
    print("=" * 80)

    print("\nSmoking binary:")
    print(
        standardized_df["smoking_binary"]
        .value_counts(dropna=False)
        .to_string()
    )

    print("\nSmoking detail:")
    print(
        standardized_df["smoking_detail"]
        .value_counts(dropna=False)
        .to_string()
    )

    print("\nAge missing:", standardized_df["age_missing_flag"].sum())
    print("Age outliers:", standardized_df["age_outlier_flag"].sum())

    if standardized_df["age_outlier_flag"].sum() > 0:
        print("\nSuspicious age records:")
        print(
            standardized_df.loc[
                standardized_df["age_outlier_flag"] == 1,
                ["PATIENT_ID", "age_numeric"]
            ].to_string(index=False)
        )

================================================================================
COHORT: TCGA_Atlas_2018
================================================================================

Smoking binary:
smoking_binary
Unknown    566

Smoking detail:
smoking_detail
Unknown    566

Age missing: 71
Age outliers: 0

================================================================================
COHORT: LUNG_MSK_2017
================================================================================

Smoking binary:
smoking_binary
Ever     583
Never    277

Smoking detail:
smoking_detail
Former     573
Never      277
Current     10

Age missing: 0
Age outliers: 2

Suspicious age records:
PATIENT_ID  age_numeric
 P-0005738            9
 P-0009339           16

================================================================================
COHORT: MSK_NPJPO_2021
================================================================================

Smoking binary:
smoking_binary
Ever     316
Never    110

Smoking detail:
smoking_detail
Ever_Unspecified    316
Never               110

Age missing: 0
Age outliers: 0

================================================================================
COHORT: MSKCC_2020
================================================================================

Smoking binary:
smoking_binary
Ever     466
Never    138

Smoking detail:
smoking_detail
Ever_Unspecified    466
Never               138

Age missing: 0
Age outliers: 0

================================================================================
COHORT: MSKCC_2023
================================================================================

Smoking binary:
smoking_binary
Unknown    1435
Ever        550
Never       216

Smoking detail:
smoking_detail
Unknown             1435
Ever_Unspecified     550
Never                216

Age missing: 0
Age outliers: 0

================================================================================
COHORT: NCI_2022
================================================================================

Smoking binary:
smoking_binary
Unknown    232

Smoking detail:
smoking_detail
Unknown    232

Age missing: 19
Age outliers: 0

================================================================================
COHORT: ONCOSG_2020
================================================================================

Smoking binary:
smoking_binary
Never      189
Ever       112
Unknown      4

Smoking detail:
smoking_detail
Never               189
Ever_Unspecified    112
Unknown               4

Age missing: 0
Age outliers: 0

In [24]:
# Step 10 — Combine standardized clinical data from all cohorts

combined_clinical_parts = []

for cohort, clinical_df in standardized_clinical_tables.items():
    cohort_df = clinical_df.copy()

    # Use plausible adult age range for modelling
    # Raw age and outlier flag are still preserved
    cohort_df["age_for_model"] = cohort_df["age_numeric"].mask(
        cohort_df["age_outlier_flag"] == 1
    )

    # Convert pack-years to numeric where available
    cohort_df["smoking_pack_years_numeric"] = pd.to_numeric(
        cohort_df["smoking_pack_years"],
        errors="coerce"
    )

    # Negative pack-year values are invalid
    cohort_df.loc[
        cohort_df["smoking_pack_years_numeric"] < 0,
        "smoking_pack_years_numeric"
    ] = np.nan

    cohort_df["pack_years_missing_flag"] = (
        cohort_df["smoking_pack_years_numeric"].isna()
    ).astype(int)

    combined_clinical_parts.append(
        cohort_df[
            [
                "COHORT",
                "PATIENT_ID",
                "age",
                "age_numeric",
                "age_for_model",
                "age_missing_flag",
                "age_outlier_flag",
                "sex",
                "smoking_status",
                "smoking_detail",
                "smoking_binary",
                "smoking_pack_years",
                "smoking_pack_years_numeric",
                "pack_years_missing_flag",
                "passive_smoking",
                "passive_smoking_standardized"
            ]
        ]
    )


combined_clinical_df = pd.concat(
    combined_clinical_parts,
    ignore_index=True
)

duplicate_count = combined_clinical_df.duplicated(
    subset=["COHORT", "PATIENT_ID"]
).sum()

clinical_combined_summary = (
    combined_clinical_df
    .groupby("COHORT")
    .agg(
        PATIENTS=("PATIENT_ID", "size"),
        AGE_USABLE_PERCENT=(
            "age_for_model",
            lambda x: round(x.notna().mean() * 100, 2)
        ),
        AGE_OUTLIERS=("age_outlier_flag", "sum"),
        SMOKING_KNOWN_PERCENT=(
            "smoking_binary",
            lambda x: round((x != "Unknown").mean() * 100, 2)
        ),
        PACK_YEARS_USABLE_PERCENT=(
            "smoking_pack_years_numeric",
            lambda x: round(x.notna().mean() * 100, 2)
        ),
        PASSIVE_SMOKING_KNOWN_PERCENT=(
            "passive_smoking_standardized",
            lambda x: round((x != "Unknown").mean() * 100, 2)
        )
    )
    .reset_index()
)

print("Combined clinical shape:", combined_clinical_df.shape)
print(
    "Duplicate COHORT + PATIENT_ID records:",
    duplicate_count
)

print("\nCombined clinical coverage:")
display(clinical_combined_summary)

Combined clinical shape: (5194, 16)
Duplicate COHORT + PATIENT_ID records: 0

Combined clinical coverage:

,COHORT,PATIENTS,AGE_USABLE_PERCENT,AGE_OUTLIERS,SMOKING_KNOWN_PERCENT,PACK_YEARS_USABLE_PERCENT,PASSIVE_SMOKING_KNOWN_PERCENT
0,LUNG_MSK_2017,860,99.77,2,100.00,0.00,0.00
1,MSKCC_2020,604,100.00,0,100.00,99.83,0.00
2,MSKCC_2023,2201,100.00,0,34.80,0.00,0.00
3,MSK_NPJPO_2021,426,100.00,0,100.00,99.77,0.00
4,NCI_2022,232,91.81,0,0.00,0.00,91.81
5,ONCOSG_2020,305,100.00,0,98.69,25.25,0.00
6,TCGA_Atlas_2018,566,87.46,0,0.00,0.00,0.00

In [25]:
# Step 11 — Merge clinical covariates with final LUAD patient dataset

FINAL_PATIENT_DATASET_PATH = (
    PROJECT_DIR
    / "luad_processed"
    / "final_luad_minion_patient_dataset.csv"
)

final_patient_df = pd.read_csv(
    FINAL_PATIENT_DATASET_PATH,
    low_memory=False
)

# Convert source cohort names to the cohort names used
# inside the final patient-level dataset
SOURCE_TO_FINAL_COHORT = {
    "TCGA_Atlas_2018": "TCGA",
    "LUNG_MSK_2017": "LUNG",
    "MSK_NPJPO_2021": "MSK_NPJPO",
    "MSKCC_2020": "MSKCC2020",
    "MSKCC_2023": "MSKCC2023",
    "NCI_2022": "NCI",
    "ONCOSG_2020": "ONCOSG"
}

clinical_for_merge = combined_clinical_df.copy()

clinical_for_merge["COHORT"] = (
    clinical_for_merge["COHORT"]
    .map(SOURCE_TO_FINAL_COHORT)
)

clinical_for_merge = clinical_for_merge.rename(
    columns={"sex": "clinical_sex"}
)

clinical_columns_to_keep = [
    "COHORT",
    "PATIENT_ID",
    "age_numeric",
    "age_for_model",
    "age_missing_flag",
    "age_outlier_flag",
    "clinical_sex",
    "smoking_detail",
    "smoking_binary",
    "smoking_pack_years_numeric",
    "pack_years_missing_flag",
    "passive_smoking_standardized"
]

clinical_for_merge = clinical_for_merge[
    clinical_columns_to_keep
].copy()

# Merge patient-level clinical features
enhanced_patient_df = final_patient_df.merge(
    clinical_for_merge,
    on=["COHORT", "PATIENT_ID"],
    how="left",
    validate="one_to_one",
    indicator=True
)

enhanced_patient_df["clinical_record_matched"] = (
    enhanced_patient_df["_merge"] == "both"
)

enhanced_patient_df["smoking_known"] = (
    enhanced_patient_df["smoking_binary"].notna()
    & enhanced_patient_df["smoking_binary"].ne("Unknown")
)

enhanced_patient_df["passive_smoking_known"] = (
    enhanced_patient_df[
        "passive_smoking_standardized"
    ].notna()
    & enhanced_patient_df[
        "passive_smoking_standardized"
    ].ne("Unknown")
)

matched_coverage = (
    enhanced_patient_df
    .groupby("COHORT")
    .agg(
        FINAL_PATIENTS=("PATIENT_ID", "size"),

        CLINICAL_MATCH_PERCENT=(
            "clinical_record_matched",
            lambda x: round(x.mean() * 100, 2)
        ),

        AGE_USABLE_PERCENT=(
            "age_for_model",
            lambda x: round(x.notna().mean() * 100, 2)
        ),

        SMOKING_KNOWN_PERCENT=(
            "smoking_known",
            lambda x: round(x.mean() * 100, 2)
        ),

        PACK_YEARS_USABLE_PERCENT=(
            "smoking_pack_years_numeric",
            lambda x: round(x.notna().mean() * 100, 2)
        ),

        PASSIVE_SMOKING_KNOWN_PERCENT=(
            "passive_smoking_known",
            lambda x: round(x.mean() * 100, 2)
        )
    )
    .reset_index()
)

print("Original final dataset shape:", final_patient_df.shape)
print("Enhanced merged shape:", enhanced_patient_df.shape)

print(
    "Matched clinical records:",
    int(enhanced_patient_df["clinical_record_matched"].sum()),
    "/",
    len(enhanced_patient_df)
)

print(
    "Unmatched patients:",
    int((~enhanced_patient_df["clinical_record_matched"]).sum())
)

print("\nActual coverage in final training population:")
display(matched_coverage)

Original final dataset shape: (3382, 13)
Enhanced merged shape: (3382, 27)
Matched clinical records: 0 / 3382
Unmatched patients: 3382

Actual coverage in final training population:

,COHORT,FINAL_PATIENTS,CLINICAL_MATCH_PERCENT,AGE_USABLE_PERCENT,SMOKING_KNOWN_PERCENT,PACK_YEARS_USABLE_PERCENT,PASSIVE_SMOKING_KNOWN_PERCENT
0,LUNG_MSK_2017,779,0.0,0.0,0.0,0.0,0.0
1,MSKCC_2020,555,0.0,0.0,0.0,0.0,0.0
2,MSKCC_2023,745,0.0,0.0,0.0,0.0,0.0
3,MSK_NPJPO_2021,396,0.0,0.0,0.0,0.0,0.0
4,NCI_2022,151,0.0,0.0,0.0,0.0,0.0
5,ONCOSG_2020,268,0.0,0.0,0.0,0.0,0.0
6,TCGA_Atlas_2018,488,0.0,0.0,0.0,0.0,0.0

In [26]:
# Step 11 corrected — Merge without changing cohort names

final_patient_df = pd.read_csv(
    FINAL_PATIENT_DATASET_PATH,
    low_memory=False
)

clinical_for_merge = combined_clinical_df.copy()

# Clean merge keys on both sides
final_patient_df["COHORT"] = (
    final_patient_df["COHORT"].astype(str).str.strip()
)

final_patient_df["PATIENT_ID"] = (
    final_patient_df["PATIENT_ID"].astype(str).str.strip()
)

clinical_for_merge["COHORT"] = (
    clinical_for_merge["COHORT"].astype(str).str.strip()
)

clinical_for_merge["PATIENT_ID"] = (
    clinical_for_merge["PATIENT_ID"].astype(str).str.strip()
)

clinical_for_merge = clinical_for_merge.rename(
    columns={"sex": "clinical_sex"}
)

clinical_for_merge = clinical_for_merge[
    [
        "COHORT",
        "PATIENT_ID",
        "age_numeric",
        "age_for_model",
        "age_missing_flag",
        "age_outlier_flag",
        "clinical_sex",
        "smoking_detail",
        "smoking_binary",
        "smoking_pack_years_numeric",
        "pack_years_missing_flag",
        "passive_smoking_standardized"
    ]
].copy()

enhanced_patient_df = final_patient_df.merge(
    clinical_for_merge,
    on=["COHORT", "PATIENT_ID"],
    how="left",
    validate="one_to_one",
    indicator=True
)

enhanced_patient_df["clinical_record_matched"] = (
    enhanced_patient_df["_merge"] == "both"
)

enhanced_patient_df["smoking_known"] = (
    enhanced_patient_df["smoking_binary"].notna()
    & enhanced_patient_df["smoking_binary"].ne("Unknown")
)

enhanced_patient_df["passive_smoking_known"] = (
    enhanced_patient_df["passive_smoking_standardized"].notna()
    & enhanced_patient_df[
        "passive_smoking_standardized"
    ].ne("Unknown")
)

matched_coverage = (
    enhanced_patient_df
    .groupby("COHORT")
    .agg(
        FINAL_PATIENTS=("PATIENT_ID", "size"),

        CLINICAL_MATCH_PERCENT=(
            "clinical_record_matched",
            lambda x: round(x.mean() * 100, 2)
        ),

        AGE_USABLE_PERCENT=(
            "age_for_model",
            lambda x: round(x.notna().mean() * 100, 2)
        ),

        SMOKING_KNOWN_PERCENT=(
            "smoking_known",
            lambda x: round(x.mean() * 100, 2)
        ),

        PACK_YEARS_USABLE_PERCENT=(
            "smoking_pack_years_numeric",
            lambda x: round(x.notna().mean() * 100, 2)
        ),

        PASSIVE_SMOKING_KNOWN_PERCENT=(
            "passive_smoking_known",
            lambda x: round(x.mean() * 100, 2)
        )
    )
    .reset_index()
)

print("Original final dataset shape:", final_patient_df.shape)
print("Enhanced merged shape:", enhanced_patient_df.shape)

print(
    "Matched clinical records:",
    int(enhanced_patient_df["clinical_record_matched"].sum()),
    "/",
    len(enhanced_patient_df)
)

print(
    "Unmatched patients:",
    int((~enhanced_patient_df["clinical_record_matched"]).sum())
)

print("\nActual coverage in final training population:")
display(matched_coverage)

Original final dataset shape: (3382, 13)
Enhanced merged shape: (3382, 27)
Matched clinical records: 3382 / 3382
Unmatched patients: 0

Actual coverage in final training population:

,COHORT,FINAL_PATIENTS,CLINICAL_MATCH_PERCENT,AGE_USABLE_PERCENT,SMOKING_KNOWN_PERCENT,PACK_YEARS_USABLE_PERCENT,PASSIVE_SMOKING_KNOWN_PERCENT
0,LUNG_MSK_2017,779,100.0,99.74,100.00,0.00,0.0
1,MSKCC_2020,555,100.0,100.00,100.00,99.82,0.0
2,MSKCC_2023,745,100.0,100.00,95.97,0.00,0.0
3,MSK_NPJPO_2021,396,100.0,100.00,100.00,99.75,0.0
4,NCI_2022,151,100.0,92.05,0.00,0.00,94.7
5,ONCOSG_2020,268,100.0,100.00,98.51,24.25,0.0
6,TCGA_Atlas_2018,488,100.0,96.11,0.00,0.00,0.0

In [27]:
# Step 12 — Validate clinical merge and sex consistency

def normalize_sex_value(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()

    if value in ["female", "f"]:
        return "Female"

    if value in ["male", "m"]:
        return "Male"

    return np.nan


enhanced_patient_df["original_sex_standardized"] = (
    enhanced_patient_df["SEX"].apply(normalize_sex_value)
)

enhanced_patient_df["clinical_sex_standardized"] = (
    enhanced_patient_df["clinical_sex"].apply(normalize_sex_value)
)

sex_comparable = (
    enhanced_patient_df["original_sex_standardized"].notna()
    & enhanced_patient_df["clinical_sex_standardized"].notna()
)

sex_mismatch = (
    sex_comparable
    & (
        enhanced_patient_df["original_sex_standardized"]
        != enhanced_patient_df["clinical_sex_standardized"]
    )
)

overall_clinical_summary = pd.DataFrame(
    {
        "Check": [
            "Total final patients",
            "Clinical records matched",
            "Usable age",
            "Known active smoking",
            "Known passive smoking",
            "Comparable sex records",
            "Sex mismatches",
            "Duplicate cohort-patient IDs"
        ],
        "Value": [
            len(enhanced_patient_df),
            int(enhanced_patient_df["clinical_record_matched"].sum()),
            int(enhanced_patient_df["age_for_model"].notna().sum()),
            int(enhanced_patient_df["smoking_known"].sum()),
            int(enhanced_patient_df["passive_smoking_known"].sum()),
            int(sex_comparable.sum()),
            int(sex_mismatch.sum()),
            int(
                enhanced_patient_df.duplicated(
                    subset=["COHORT", "PATIENT_ID"]
                ).sum()
            )
        ]
    }
)

print("Final clinical sanity-check summary:")
display(overall_clinical_summary)

print("\nOverall usable percentages:")
print(
    "Age:",
    round(
        enhanced_patient_df["age_for_model"].notna().mean() * 100,
        2
    ),
    "%"
)

print(
    "Active smoking:",
    round(
        enhanced_patient_df["smoking_known"].mean() * 100,
        2
    ),
    "%"
)

if sex_mismatch.any():
    print("\nSex mismatch records:")
    display(
        enhanced_patient_df.loc[
            sex_mismatch,
            [
                "COHORT",
                "PATIENT_ID",
                "SEX",
                "clinical_sex"
            ]
        ]
    )
else:
    print("\nSex validation passed: no mismatches found.")

Final clinical sanity-check summary:

                          Check  Value
0          Total final patients   3382
1      Clinical records matched   3382
2                    Usable age   3349
3          Known active smoking   2709
4         Known passive smoking    143
5        Comparable sex records   3382
6                Sex mismatches      0
7  Duplicate cohort-patient IDs      0

Overall usable percentages:
Age: 99.02 %
Active smoking: 80.1 %

Sex validation passed: no mismatches found.

In [30]:
# Step 13 — Save final clinical covariates and TXT summary
# Running this cell again overwrites the same two files.
# Passive smoking is completely excluded.

from pathlib import Path
import pandas as pd

IMPROVED_OUTPUT_DIR = (
    PROJECT_DIR
    / "luad_processeed_data"
)

IMPROVED_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

CLINICAL_OUTPUT_PATH = (
    IMPROVED_OUTPUT_DIR
    / "luad_improved_clinical_covariates.csv"
)

SUMMARY_TXT_PATH = (
    IMPROVED_OUTPUT_DIR
    / "luad_improved_clinical_summary.txt"
)

# Remove old CSV summary created by the previous code
OLD_SUMMARY_CSV_PATH = (
    IMPROVED_OUTPUT_DIR
    / "luad_improved_clinical_summary.csv"
)

if OLD_SUMMARY_CSV_PATH.exists():
    OLD_SUMMARY_CSV_PATH.unlink()
    print("Removed old summary CSV:", OLD_SUMMARY_CSV_PATH)


# ---------------------------------------------------------
# Prepare final clinical dataset
# ---------------------------------------------------------

clinical_output_df = enhanced_patient_df.copy()

clinical_output_df["age_unusable_flag"] = (
    clinical_output_df["age_for_model"].isna()
).astype(int)

clinical_output_df["smoking_unknown_flag"] = (
    clinical_output_df["smoking_binary"].isna()
    | clinical_output_df["smoking_binary"].eq("Unknown")
).astype(int)

# Passive-smoking columns are not selected
clinical_output_df = clinical_output_df[
    [
        "COHORT",
        "SAMPLE_ID",
        "PATIENT_ID",

        "SEX",
        "sex_encoded",

        "age_numeric",
        "age_for_model",
        "age_unusable_flag",
        "age_outlier_flag",

        "smoking_detail",
        "smoking_binary",
        "smoking_unknown_flag",

        "smoking_pack_years_numeric",
        "pack_years_missing_flag",

        "clinical_record_matched"
    ]
].copy()

clinical_output_df = clinical_output_df.sort_values(
    ["COHORT", "PATIENT_ID"]
).reset_index(drop=True)


# ---------------------------------------------------------
# Save CSV — overwrite existing file
# ---------------------------------------------------------

clinical_output_df.to_csv(
    CLINICAL_OUTPUT_PATH,
    index=False,
    mode="w"
)


# ---------------------------------------------------------
# Calculate overall summary
# ---------------------------------------------------------

total_patients = len(clinical_output_df)

usable_age_count = int(
    clinical_output_df["age_for_model"].notna().sum()
)

known_smoking_count = int(
    clinical_output_df["smoking_binary"]
    .isin(["Never", "Ever"])
    .sum()
)

unknown_smoking_count = int(
    clinical_output_df["smoking_unknown_flag"].sum()
)

age_outlier_count = int(
    clinical_output_df["age_outlier_flag"].sum()
)

duplicate_count = int(
    clinical_output_df.duplicated(
        subset=["COHORT", "PATIENT_ID"]
    ).sum()
)

clinical_match_count = int(
    clinical_output_df["clinical_record_matched"].sum()
)

passive_columns = [
    column
    for column in clinical_output_df.columns
    if "passive" in column.lower()
]


# ---------------------------------------------------------
# Create cohort-wise summary
# ---------------------------------------------------------

cohort_summary = (
    clinical_output_df
    .groupby("COHORT")
    .agg(
        total_patients=("PATIENT_ID", "size"),

        usable_age_count=(
            "age_for_model",
            lambda x: int(x.notna().sum())
        ),

        known_smoking_count=(
            "smoking_binary",
            lambda x: int(x.isin(["Never", "Ever"]).sum())
        ),

        unknown_smoking_count=(
            "smoking_unknown_flag",
            "sum"
        ),

        age_outlier_count=(
            "age_outlier_flag",
            "sum"
        )
    )
    .reset_index()
)

cohort_summary["usable_age_percent"] = (
    cohort_summary["usable_age_count"]
    / cohort_summary["total_patients"]
    * 100
).round(2)

cohort_summary["known_smoking_percent"] = (
    cohort_summary["known_smoking_count"]
    / cohort_summary["total_patients"]
    * 100
).round(2)


# ---------------------------------------------------------
# Write TXT summary — overwrite existing file
# ---------------------------------------------------------

summary_lines = [
    "LUAD IMPROVED CLINICAL COVARIATES SUMMARY",
    "=" * 60,
    "",
    f"Total patients: {total_patients}",
    f"Matched clinical records: {clinical_match_count}",
    f"Duplicate COHORT + PATIENT_ID records: {duplicate_count}",
    "",
    f"Usable age records: {usable_age_count}",
    f"Usable age percentage: "
    f"{usable_age_count / total_patients * 100:.2f}%",
    f"Age outlier records: {age_outlier_count}",
    "",
    f"Known smoking records: {known_smoking_count}",
    f"Known smoking percentage: "
    f"{known_smoking_count / total_patients * 100:.2f}%",
    f"Unknown smoking records: {unknown_smoking_count}",
    "",
    "Passive smoking included: No",
    f"Passive smoking columns found: {passive_columns}",
    "",
    "PACK-YEARS NOTE:",
    "Pack-years were preserved for auditing and optional experiments.",
    "They will not be used in the main model because coverage is inconsistent.",
    "",
    "COHORT-WISE SUMMARY",
    "=" * 60
]

for _, row in cohort_summary.iterrows():
    summary_lines.extend(
        [
            "",
            f"Cohort: {row['COHORT']}",
            f"  Total patients: {int(row['total_patients'])}",
            f"  Usable age: {int(row['usable_age_count'])} "
            f"({row['usable_age_percent']:.2f}%)",
            f"  Known smoking: {int(row['known_smoking_count'])} "
            f"({row['known_smoking_percent']:.2f}%)",
            f"  Unknown smoking: "
            f"{int(row['unknown_smoking_count'])}",
            f"  Age outliers: {int(row['age_outlier_count'])}"
        ]
    )

with open(
    SUMMARY_TXT_PATH,
    mode="w",
    encoding="utf-8"
) as summary_file:
    summary_file.write("\n".join(summary_lines))


# ---------------------------------------------------------
# Final verification
# ---------------------------------------------------------

print("\nClinical CSV saved:")
print(CLINICAL_OUTPUT_PATH)

print("\nTXT summary saved:")
print(SUMMARY_TXT_PATH)

print("\nCSV shape:", clinical_output_df.shape)
print("Duplicate patients:", duplicate_count)
print("Passive smoking columns:", passive_columns)

print("\nFiles currently created by this cell:")
print("1.", CLINICAL_OUTPUT_PATH.name)
print("2.", SUMMARY_TXT_PATH.name)

Clinical CSV saved:
C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processeed_data\luad_improved_clinical_covariates.csv

TXT summary saved:
C:\Users\LAPTOP\Downloads\luad_reserch_code\luad_processeed_data\luad_improved_clinical_summary.txt

CSV shape: (3382, 15)
Duplicate patients: 0
Passive smoking columns: []

Files currently created by this cell:
1. luad_improved_clinical_covariates.csv
2. luad_improved_clinical_summary.txt

In [31]:
# Step 14 — Compare stage distribution in smoking-missing cohorts

SMOKING_UNAVAILABLE_COHORTS = [
    "NCI_2022",
    "TCGA_Atlas_2018"
]

stage_count_by_cohort = pd.crosstab(
    enhanced_patient_df["COHORT"],
    enhanced_patient_df["STAGE_BINARY"]
)

stage_percent_by_cohort = (
    pd.crosstab(
        enhanced_patient_df["COHORT"],
        enhanced_patient_df["STAGE_BINARY"],
        normalize="index"
    )
    * 100
).round(2)

print("Stage counts by cohort:")
display(stage_count_by_cohort)

print("\nStage percentages by cohort:")
display(stage_percent_by_cohort)


# Compare cohorts with and without smoking data
stage_comparison_df = enhanced_patient_df[
    ["COHORT", "STAGE_BINARY"]
].copy()

stage_comparison_df["SMOKING_COVERAGE_GROUP"] = np.where(
    stage_comparison_df["COHORT"].isin(
        SMOKING_UNAVAILABLE_COHORTS
    ),
    "Smoking completely unavailable",
    "Smoking partly/fully available"
)

group_stage_counts = pd.crosstab(
    stage_comparison_df["SMOKING_COVERAGE_GROUP"],
    stage_comparison_df["STAGE_BINARY"]
)

group_stage_percentages = (
    pd.crosstab(
        stage_comparison_df["SMOKING_COVERAGE_GROUP"],
        stage_comparison_df["STAGE_BINARY"],
        normalize="index"
    )
    * 100
).round(2)

print("\nGrouped stage counts:")
display(group_stage_counts)

print("\nGrouped stage percentages:")
display(group_stage_percentages)

Stage counts by cohort:

STAGE_BINARY     Advanced  Early
COHORT
LUNG_MSK_2017         695     84
MSKCC_2020             58    497
MSKCC_2023            302    443
MSK_NPJPO_2021          0    396
NCI_2022               30    121
ONCOSG_2020            94    174
TCGA_Atlas_2018       107    381

Stage percentages by cohort:

STAGE_BINARY     Advanced   Early
COHORT
LUNG_MSK_2017       89.22   10.78
MSKCC_2020          10.45   89.55
MSKCC_2023          40.54   59.46
MSK_NPJPO_2021       0.00  100.00
NCI_2022            19.87   80.13
ONCOSG_2020         35.07   64.93
TCGA_Atlas_2018     21.93   78.07

Grouped stage counts:

STAGE_BINARY                    Advanced  Early
SMOKING_COVERAGE_GROUP
Smoking completely unavailable       137    502
Smoking partly/fully available      1149   1594

Grouped stage percentages:

STAGE_BINARY                    Advanced  Early
SMOKING_COVERAGE_GROUP
Smoking completely unavailable     21.44  78.56
Smoking partly/fully available     41.89  58.11